---
id: postgresql-conference-japan-2025
base_name: pgroonga-with-semantic-search
tags: [rabbit, postgresql, groonga, pgroonga, pgcon25j, fts]
presentation_date: 2025-11-21
presentation_start_time:
presentation_end_time:
version: 1.0.2
licenses: [CC-BY-SA-4.0, CC-BY-3.0, The PostgreSQL Licence]
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
source_code_uri:
author:
  markup_language: :rd
  name: Horimoto Yasuhiro
  email: horimoto@clear-code.com
  rubygems_user: komainu8
  slideshare_user:
  speaker_deck_user:
